In [ ]:
---
title: "Cleaning Data"
execute:
    echo: true
    eval: true
---

# Data Cleaning {.unnumbered}

#### Remove not valid numbers {.unnumbered}
If there a not valid numbers in the data, you have to be very careful. <br> You have to be sure how to handle your data and what a not valid number means in your context. <br> There are different ways to handle not valid numbers. You can remove them, replace them with a valid number, or just ignore them.
#### Search about specific elements in the array: {.unnumbered}

`NaN` means "Not a Number". It is a special floating point value that is used to represent the result of an invalid operation, such as dividing by zero. It is also used to represent missing data.

In [ ]:
a = np.array([[1, 2],[3, 4],[5, 6], [np.nan, 8]])
print(a)
b = np.isnan(a)
print("Check if there is any NaN in the array:\n", b)
print("There are NaNs in the array!" if True
       in b else "There are no NaNs in the array.")
# remove NaNs from the array; 
# ~ is the negation operator it inverts the boolean values
print("Remove NaNs from the array: \n", a[~np.isnan(a)])
# replace NaNs with 0
print("Replace NaNs with 0: \n", np.nan_to_num(a)) 
# replace NaNs with 1
print("Replace NaNs with 1: \n", np.nan_to_num(a, nan=1)) 
# ignore NaNs and calculate the mean
print("Ignore NaNs and calculate the mean: \n", np.nanmean(a))


[[ 1.  2.]
 [ 3.  4.]
 [ 5.  6.]
 [nan  8.]]
Check if there is any NaN in the array:
 [[False False]
 [False False]
 [False False]
 [ True False]]
There are NaNs in the array!
Remove NaNs from the array: 
 [1. 2. 3. 4. 5. 6. 8.]
Replace NaNs with 0: 
 [[1. 2.]
 [3. 4.]
 [5. 6.]
 [0. 8.]]
Replace NaNs with 1: 
 [[1. 2.]
 [3. 4.]
 [5. 6.]
 [1. 8.]]
Ignore NaNs and calculate the mean: 
 4.142857142857143


Also `inf` is a special floating point value that is used to represent the result of an operation that is too large to represent as a number.

In [ ]:
arr_inf = np.array([1, 2, 3, np.inf, 5, 6, np.inf])
print(arr_inf)
print("Check if there is any inf in the array:\n", np.isinf(arr_inf))
print("There are inf in the array!" if True 
      in np.isinf(arr_inf) else "There are no inf in the array.")
# remove inf from the array
print("Remove inf from the array: \n", arr_inf[~np.isinf(arr_inf)])


[ 1.  2.  3. inf  5.  6. inf]
Check if there is any inf in the array:
 [False False False  True False False  True]
There are inf in the array!
Remove inf from the array: 
 [1. 2. 3. 5. 6.]
